name: Telegram Create Notifications
on: [push, release, pull_request, issues, issue_comment, create]

jobs:
  create-notify:
    name: Custom Create Notification
    runs-on: ubuntu-latest
    if: github.event_name == 'create'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Custom create notification
        run: python .github/scripts/telegram_notify.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}

  default-notify:
    name: Default Notification
    runs-on: ubuntu-latest
    if: github.event_name != 'create' && github.event_name != 'push'
    steps:
      - name: Notify via EverythingSuckz Action
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          topic_id: 6
